name: Expresion

on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: number
      nombre:
        description: 'Nombre'
        required: true
        default: 'Valor default'
        type: string
  push:
    branches: ["main"]
jobs:
  mayor:
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad
      - name: Mostrar nombre de evento
        run: echo ${{ github.event_name }}
      - name: Mostrar usuario
        run: echo ${{ github.actor }}

  menor:
    if: ${{ inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Corrre script meno
        run: echo ${{ inputs.nombre }} es menor de edad
